name: FlightTracker
options:
  bundleIdPrefix: com.example
  createIntermediateGroups: true
  deploymentTarget:
    iOS: 16.0
settings:
  DEVELOPMENT_TEAM: ""
targets:
  FlightTracker:
    type: application
    platform: iOS
    sources:
      - path: FlightTracker
        createIntermediateGroups: true
    settings:
      INFOPLIST_FILE: FlightTracker/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.example.FlightTracker
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_VERSION: 5.0
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight" 